Lesson10
andreiabramovsky/testGuru pull request #10
Opened 2023-02-05 14:02 UTC by andreiabramovsky

2023-02-06 05:17 UTC, VidgarVii requested changes

2023-02-06 05:17 UTC, VidgarVii commented on app/views/shared/_errors.html.erb
> +<% end %>
No new lina at end of file

2023-02-06 05:17 UTC, VidgarVii commented on app/views/shared/_navigation.html.erb
> +      <%= link_to 'Exit', logout_path, method: :post %>
Это лучше сделать HTTP-методом DELETE, чтоб соблюдалась семантика REST. Ресурсы удаляют только методом DELETE

2023-02-06 05:17 UTC, VidgarVii commented on db/migrate/20230205112927_add_password_digest_to_users.rb
> +    add_column :users, :password_digest, :string
судя по коду юзер может быть без пароля?!

2023-02-07 05:05 UTC, VidgarVii requested changes

2023-02-07 05:05 UTC, VidgarVii commented on db/migrate/20230206160259_add_password_to_users.rb
> +  end
вторая миграция на изменения одной таблицы явно лишняя. Кол-во миграций должно быть минимальным. Уже проходили на теме миграций

2023-02-07 05:05 UTC, VidgarVii commented on db/migrate/20230205112927_add_password_digest_to_users.rb
> +    add_column :users, :password_digest, :string
не исправлено

2023-02-07 05:05 UTC, VidgarVii commented on app/views/shared/_navigation.html.erb
> +      <%= link_to 'Exit', destroy_user_session_path, method: :delete %>
не работает

2023-02-09 21:41 UTC, andreiabramovsky commented on db/migrate/20230205112927_add_password_digest_to_users.rb
> +    add_column :users, :password_digest, :string
Так ведь пароль в password_digest хранится зашифрованный. Разве нет?

2023-02-09 21:41 UTC, andreiabramovsky commented on db/migrate/20230206160259_add_password_to_users.rb
> +  end
Убрал

2023-02-10 07:14 UTC, VidgarVii requested changes

2023-02-10 07:14 UTC, VidgarVii commented on db/migrate/20230205112927_add_password_digest_to_users.rb
> +    add_column :users, :password_digest, :string
да. зашифрованный. Но проблема не в этом. 
https://github.com/andreiabramovsky/testGuru/pull/10/files#r1096954259

2023-02-10 17:29 UTC, merged