Lesson4
andreiabramovsky/testGuru pull request #4
Opened 2022-12-10 12:27 UTC by andreiabramovsky

2022-12-11 07:58 UTC, VidgarVii requested changes

2022-12-11 07:58 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins('JOIN categories ON tests.category_id = categories.id')
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2022-12-11 07:58 UTC, VidgarVii commented on db/seeds.rb
> +    {body: 'Yes', question_id: questions.[0].id, correct: true},
Проверял работу сидов? Тут запрашивается переменная которой еще нет.

2022-12-11 18:19 UTC, andreiabramovsky commented on db/seeds.rb
> +    {body: 'Yes', question_id: questions.[0].id, correct: true},
То есть answers создастся впоследствии, потому что ответов пока нет. Как и UserTests, потому что пройденных тестов нет. Верно? А сиды как нужно проверить? Вот это накатить rails db:seed ? Или я не прав?

2022-12-12 04:06 UTC, VidgarVii requested changes

2022-12-12 04:06 UTC, VidgarVii commented on db/seeds.rb
> +    {body: 'Yes', question_id: questions.[0].id, correct: true},
rails db:seed

2022-12-12 18:46 UTC, merged